
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"MenuIndexPage","number":71,"title":"Menu index/edit page","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-1/pull/71"},{"author":{"id":"U_kgDOB0qFUw","is_bot":false,"login":"vcnardi524","name":"victor Nardi"},"headRefName":"Victor-HelpRequests","number":66,"title":"Victor help requests","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-1/pull/66"}]
