
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBtn4Uw","is_bot":false,"login":"shashank790","name":""},"headRefName":"Shashank-Articles","number":77,"title":"sb added Articles.json db migration file","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-1/pull/77"},{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"Jenil-RecommendationRequests","number":76,"title":"Jenil recommendation requests","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-1/pull/76"}]
