name: 98 - Copy Issues to Project

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
   inputs:
      project:
        type: number
        description: number of project
jobs:

  copyIssuesToProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/${{inputs.project}}
          github-token: ${{ github.token }}

      
